all: subnet-tools

subnet-tools: src/*.c src/*.h
	cd src; make -f Makefile.bsd subnet-tools
	mv src/subnet-tools .

test-printf: src/*.c src/*.h
	cd src; make test-printf
	mv src/test-printf .

test: src/*.c src/*.h
	cd src; make test
